-- Procedure Definitions
CREATE OR REPLACE PROCEDURE store_demo_db.store_demo_sch.ADD_CUSTOMER (
  p_FIRST_NAME IN VARCHAR2,
  p_LAST_NAME IN VARCHAR2,
  p_EMAIL IN VARCHAR2,
  p_ADDRESS IN VARCHAR2,
  p_PHONE IN NUMBER,
  p_NEW_CUSTOMER_ID OUT NUMBER
) AS
BEGIN
  INSERT INTO store_demo_db.store_demo_sch.CUSTOMERS (FIRST_NAME, LAST_NAME, EMAIL, ADDRESS, PHONE)
  VALUES (p_FIRST_NAME, p_LAST_NAME, p_EMAIL, p_ADDRESS, p_PHONE)
  RETURNING CUSTOMER_ID INTO p_NEW_CUSTOMER_ID;
END ADD_CUSTOMER;

CREATE OR REPLACE PROCEDURE store_demo_db.store_demo_sch.ADD_PRODUCT (
  p_PRODUCT_NAME IN VARCHAR2,
  p_DESCRIPTION IN VARCHAR2,
  p_PRICE IN NUMBER,
  p_STOCK_QUANTITY IN NUMBER,
  p_NEW_PRODUCT_ID OUT NUMBER
) AS
BEGIN
  INSERT INTO store_demo_db.store_demo_sch.PRODUCTS (PRODUCT_NAME, DESCRIPTION, PRICE, STOCK_QUANTITY)
  VALUES (p_PRODUCT_NAME, p_DESCRIPTION, p_PRICE, p_STOCK_QUANTITY)
  RETURNING PRODUCT_ID INTO p_NEW_PRODUCT_ID;
END ADD_PRODUCT;

CREATE OR REPLACE PROCEDURE store_demo_db.store_demo_sch.PLACE_ORDER (
  p_CUSTOMER_ID IN NUMBER,
  p_ORDER_DATE IN DATE,
  p_TOTAL IN NUMBER,
  p_NEW_ORDER_ID OUT NUMBER
) AS
BEGIN
  INSERT INTO store_demo_db.store_demo_sch.ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL)
  VALUES (p_CUSTOMER_ID, p_ORDER_DATE, p_TOTAL)
  RETURNING ORDER_ID INTO p_NEW_ORDER_ID;
END PLACE_ORDER;

CREATE OR REPLACE PROCEDURE store_demo_db.store_demo_sch.ADD_ORDER_ITEM (
  p_ORDER_ID IN NUMBER,
  p_PRODUCT_ID IN NUMBER,
  p_QUANTITY IN NUMBER,
  p_UNIT_PRICE IN NUMBER,
  p_NEW_ORDER_ITEM_ID OUT NUMBER
) AS
BEGIN
  INSERT INTO store_demo_db.store_demo_sch.ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE)
  VALUES (p_ORDER_ID, p_PRODUCT_ID, p_QUANTITY, p_UNIT_PRICE)
  RETURNING ORDER_ITEM_ID INTO p_NEW_ORDER_ITEM_ID;
END ADD_ORDER_ITEM;

CREATE OR REPLACE PROCEDURE store_demo_db.store_demo_sch.MAKE_PAYMENT (
  p_ORDER_ID IN NUMBER,
  p_PAYMENT_DATE IN DATE,
  p_PAYMENT_METHOD IN VARCHAR2,
  p_AMOUNT IN NUMBER,
  p_NEW_PAYMENT_ID OUT NUMBER
) AS
BEGIN
  INSERT INTO store_demo_db.store_demo_sch.PAYMENTS (ORDER_ID, PAYMENT_DATE, PAYMENT_METHOD, AMOUNT)
  VALUES (p_ORDER_ID, p_PAYMENT_DATE, p_PAYMENT_METHOD, p_AMOUNT)
  RETURNING PAYMENT_ID INTO p_NEW_PAYMENT_ID;
END MAKE_PAYMENT;

CREATE OR REPLACE PROCEDURE store_demo_db.store_demo_sch.ADD_INVENTORY (
  p_WAREHOUSE_ID IN NUMBER,
  p_PRODUCT_ID IN NUMBER,
  p_QUANTITY IN NUMBER,
  p_NEW_INVENTORY_ID OUT NUMBER
) AS
BEGIN
  INSERT INTO store_demo_db.store_demo_sch.INVENTORY (WAREHOUSE_ID, PRODUCT_ID, QUANTITY)
  VALUES (p_WAREHOUSE_ID, p_PRODUCT_ID, p_QUANTITY)
  RETURNING INVENTORY_ID INTO p_NEW_INVENTORY_ID;
END ADD_INVENTORY;

CREATE OR REPLACE PROCEDURE store_demo_db.store_demo_sch.ADD_WAREHOUSE (
  p_WAREHOUSE_NAME IN VARCHAR2,
  p_LOCATION IN VARCHAR2,
  p_NEW_WAREHOUSE_ID OUT NUMBER
) AS
BEGIN
  INSERT INTO store_demo_db.store_demo_sch.WAREHOUSES (WAREHOUSE_NAME, LOCATION)
  VALUES (p_WAREHOUSE_NAME, p_LOCATION)
  RETURNING WAREHOUSE_ID INTO p_NEW_WAREHOUSE_ID;
END ADD_WAREHOUSE;
