


  CREATE OR REPLACE SYNONYM "XDMADM"."TOP_PROD_RECMND_LOAD" FOR "XDMADM"."TOP_PROD_RECMND_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."BAK_SYN_CUST_CORP" FOR "XDMADM"."BAK_CUST_CORP";




  CREATE OR REPLACE SYNONYM "XDMADM"."PIM_CORP_AGGR" FOR "XDMADM"."PIM_CORP_AGGR_A";




  CREATE OR REPLACE SYNONYM "XDMADM"."CUST_PLUS_PRSPCT_CORP" FOR "XDMADM"."CUST_PLUS_PRSPCT_CORP_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."CUST_AVG_PNTRTN_RATE" FOR "XDMADM"."CUST_AVG_PNTRTN_RATE_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."CUST_WK_AGGR_LOAD" FOR "XDMADM"."CUST_WK_AGGR_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."CUST_CLSFCTN_CORP_WK" FOR "XDMADM"."CUST_CLSFCTN_CORP_WK_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."SYN_CUST_CORP_20140517" FOR "XDMADM"."CUST_CORP_20140517";




  CREATE OR REPLACE SYNONYM "XDMADM"."SALES_SUMM_PYR_WKLY" FOR "XDMADM"."SALES_SUMM_PYR_WKLY_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."KEY_VAL_ITMS" FOR "XDMADM"."KEY_VAL_ITMS_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."SALES_SUMM_CLNDRMO_CORP" FOR "XDMADM"."SALES_SUMM_CLNDRMO_CORP_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."SALES_SUMM_PYR_PRJ_LOAD" FOR "XDMADM"."SALES_SUMM_PYR_PRJ_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."SALES_SUMM_PYR_AGGR" FOR "XDMADM"."SALES_SUMM_PYR_AGGR_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."CUST_WK_AGGR" FOR "XDMADM"."CUST_WK_AGGR_A";




  CREATE OR REPLACE SYNONYM "XDMADM"."SALES_SUMM_PYR_WKLY_LOAD" FOR "XDMADM"."SALES_SUMM_PYR_WKLY_A";




  CREATE OR REPLACE SYNONYM "XDMADM"."PIM_CORP_MRCH_AGGR" FOR "XDMADM"."PIM_CORP_MRCH_AGGR_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."SALES_RGN_WK_PRJ" FOR "XDMADM"."SALES_RGN_WK_PRJ_A";




  CREATE OR REPLACE SYNONYM "XDMADM"."DDMADM_SIS_SLS_DTL_CORP" FOR "DDMADM"."SIS_SLS_DTL_CORP"@"IWSTGPRD_DBLINK.MAIN.USFOOD.COM";




  CREATE OR REPLACE SYNONYM "XDMADM"."CKBK_LNS_AGGR" FOR "XDMADM"."CKBK_LNS_AGGR_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."SYN_SLS_RNK_ORG" FOR "XDMADM"."SLS_RNK_ORG";




  CREATE OR REPLACE SYNONYM "XDMADM"."SALES_MKTPLUS_AGGR" FOR "XDMADM"."SALES_MKTPLUS_AGGR_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."CKBK_RSN_EXCLD_LOAD" FOR "XDMADM"."CKBK_RSN_EXCLD_A";




  CREATE OR REPLACE SYNONYM "XDMADM"."CUST_WK_AGGR_TST" FOR "XDMADM"."CUST_WK_AGGR_B_TST";




  CREATE OR REPLACE SYNONYM "XDMADM"."CUST_WK_AGGR_LOAD_TST" FOR "XDMADM"."CUST_WK_AGGR_A_TST";




  CREATE OR REPLACE SYNONYM "XDMADM"."CKBK_LNS_AGGR_LOAD" FOR "XDMADM"."CKBK_LNS_AGGR_A";




  CREATE OR REPLACE SYNONYM "XDMADM"."CUST_CLSFCTN_CORP_WK_LOAD" FOR "XDMADM"."CUST_CLSFCTN_CORP_WK_A";




  CREATE OR REPLACE SYNONYM "XDMADM"."TOP_PROD_RECMND" FOR "XDMADM"."TOP_PROD_RECMND_A";




  CREATE OR REPLACE SYNONYM "XDMADM"."PIM_CORP_MRCH_AGGR_LOAD" FOR "XDMADM"."PIM_CORP_MRCH_AGGR_A";




  CREATE OR REPLACE SYNONYM "XDMADM"."SALES_RGN_WK_AGGR" FOR "XDMADM"."SALES_RGN_WK_AGGR_A";




  CREATE OR REPLACE SYNONYM "XDMADM"."SALES_SUMM_CUST_MRCH" FOR "XDMADM"."SALES_SUMM_CUST_MRCH_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."SALES_SUMM_MRCH_AGGR" FOR "XDMADM"."SALES_SUMM_MRCH_AGGR_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."SYN_CUST_CORP" FOR "XDMADM"."CUST_CORP";




  CREATE OR REPLACE SYNONYM "XDMADM"."CKBK_RSN_EXCLD" FOR "XDMADM"."CKBK_RSN_EXCLD_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."CUST_CORP_PYR_AGGR" FOR "XDMADM"."CUST_CORP_PYR_AGGR_A";




  CREATE OR REPLACE SYNONYM "XDMADM"."SALES_SUMM_PYR_PRJ" FOR "XDMADM"."SALES_SUMM_PYR_PRJ_A";




  CREATE OR REPLACE SYNONYM "XDMADM"."SALES_SUMM_PYR_AGGR_LOAD" FOR "XDMADM"."SALES_SUMM_PYR_AGGR_A";




  CREATE OR REPLACE SYNONYM "XDMADM"."KEY_VAL_ITMS_LOAD" FOR "XDMADM"."KEY_VAL_ITMS_A";




  CREATE OR REPLACE SYNONYM "XDMADM"."SYN_DIV_CORP" FOR "XDMADM"."DIV_CORP";




  CREATE OR REPLACE SYNONYM "XDMADM"."SYN_CUST_CLSFCTN_CORP" FOR "XDMADM"."CUST_CLSFCTN_CORP";




  CREATE OR REPLACE SYNONYM "XDMADM"."PIM_CORP_AGGR_LOAD" FOR "XDMADM"."PIM_CORP_AGGR_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."SALES_SUMM_MRCH_AGGR_LOAD" FOR "XDMADM"."SALES_SUMM_MRCH_AGGR_A";




  CREATE OR REPLACE SYNONYM "XDMADM"."CUST_CORP_PYR_AGGR_LOAD" FOR "XDMADM"."CUST_CORP_PYR_AGGR_B";




  CREATE OR REPLACE SYNONYM "XDMADM"."CUST_AVG_PNTRTN_RATE_LOAD" FOR "XDMADM"."CUST_AVG_PNTRTN_RATE_A";




 